import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import Providers from "./providers";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${dm_sans.className}`}>
          <div className="root-layout">
            <Providers>{children}</Providers>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
